server:
    port: 8888
    mode: "dev"

mysql:
    host: mysql_container #127.0.0.1
    port: 3306 #33306
    username: root
    password: root1234
    dbName: goshop
    maxIdleConns: 10
    maxOpenConns: 100
    connMaxLifetime: 3600 # in seconds

logger:
    log_level: debug
    file_log_name: "./storages/logs/dev.001.log"
    max_size: 500 # in megabytes
    max_backups: 3
    max_age: 28 # in days
    compress: true
redis:
    host: redis_container #127.0.0.1
    port: 6379 #6381
    password:
    database: 0
